//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Commercial
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDetail
    {
        public int Id { get; set; }
        public int MasterId { get; set; }
        public int ProductId { get; set; }
        public string HSCode { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> KG { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> Total { get; set; }
    
        public virtual tblMaster tblMaster { get; set; }
        public virtual tblProduct tblProduct { get; set; }
    }
}
