//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Commercial
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblMaster()
        {
            this.tblDetails = new HashSet<tblDetail>();
        }
    
        public int Id { get; set; }
        public int BankId { get; set; }
        public int SupplierId { get; set; }
        public string LCNo { get; set; }
        public System.DateTime LCDate { get; set; }
        public string Address { get; set; }
        public string IRCNo { get; set; }
        public string PINo { get; set; }
        public string PIValue { get; set; }
        public Nullable<decimal> LCAmount { get; set; }
        public Nullable<decimal> TTAmount { get; set; }
        public Nullable<decimal> FOBPrice { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> FreightCharge { get; set; }
        public string ContainerQuantity { get; set; }
        public Nullable<decimal> CustomsDuty { get; set; }
    
        public virtual tblBank tblBank { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDetail> tblDetails { get; set; }
        public virtual tblSupplier tblSupplier { get; set; }
    }
}
