//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Commercial
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        public int Id { get; set; }
        public Nullable<int> RolesId { get; set; }
        public string UserName { get; set; }
        public string FullName { get; set; }
        public string Designation { get; set; }
        public string Passward { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
